version: 2.1

jobs:

  checkout_and_build:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v3-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v3-npm-deps-{{ .Branch }}
            - v3-npm-deps-

      - run:
          name: install NPM dependencies
          command: |
            sudo npm install -g npm
            sudo apt-get update
            npm install

      - save_cache:
          key: v3-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          # Should create dist/ which will be stored by persist_to_workspace
          name: Build
          command: |
            npm run build

      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .local

  lint:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: run lint
          command: |
            npm run lint

workflows:
  version: 2.1

  build_and_publish:
    jobs:

      - checkout_and_build

      - lint:
          requires:
            - checkout_and_build
